### ISSUE TITLE
Unable to delete volumes without deletionVipPool and deletionViewPolicy

### ISSUE THREAD

**Issue by datamattsson** [vast-data/vast-csi#10]
I'm not able to delete volumes properly unless I specify these parameters in the Helm chart. The `PV` is stuck `Released`.

 ```
deletionVipPool: "my-pool"
deletionViewPolicy: "my-view-policy"
```

while the `values.yaml` states on both parameters:

```
# - value is not required when VAST cluster version is 4.6.0 onwards and `DontUseTrashApi` flag is set to false
```

I'm using VAST cluster version 4.7.0 and the `DontUseTrashApi` is set to the default of `false`.

This is the error from the controller:

```
2024-09-17 18:11:14,479|ERROR  |77E8CDE40B38|vast-csi       | Exception during DeleteVolume
Traceback (most recent call last):
  vast_csi/server.py:174 ...................... wrapper >> ret = func(self, request=request, context=context, **params)
  */easypy/misc.py:113 .......................... inner >> return func(*args, **kwargs)
  vast_csi/server.py:486 ................. DeleteVolume >> self._delete_data_from_storage(vms_session, quota.path, quota.tenant_id)
  vast_csi/server.py:414 .... _delete_data_from_storage >> assert CONF.deletion_view_policy, (
AssertionError: Ensure that deletionViewPolicy is properly configured in your Helm configuration to perform local volume deletion.
```

This is impractical in an environment with multiple VAST systems.

**Comment by koreno** [comment]
Hi @datamattsson!
FYI this github repo is here mainly for transparency and open-source considerations. For proper support please go through VAST's Customer Support channels, so you get the proper attention.

Indeed it's hard to know for sure without detailed controller logs. My guess is that there's some configuration step missing on the VAST side that's preventing the driver from using the "Trash API". You can look for `Attempting trash API to delete` and `Trash API not available` in the logs. I'm assuming you're running VCSI 2.4.1?

As for using multiple VAST systems - Indeed this is a legacy configuration that will soon become deprecated, precisely for this impracticality reason. Multi-system environments are expected to run 4.7+ versions with the Trash Folder access enabled, so that the driver never has to rely on deletion view-policy/vip-pool.

**Comment by datamattsson** [comment]
> FYI this github repo is here mainly for transparency and open-source considerations. For proper support please go through VAST's Customer Support channels, so you get the proper attention.

I'm not a customer. I'm a partner and don't have a support channel.

> You can look for `Attempting trash API to delete` and `Trash API not available` in the logs. I'm assuming you're running VCSI 2.4.1?

I'm using 2.4.1 and this is the "Attempting":

```
2024-09-17 19:26:54,367|INFO   |7D6A53EA9B38|vast-csi       | Attempting trash API to delete /export/pvc-4d9fe6b0-a16a-4587-a3c9-187bc0af2d72
2024-09-17 19:26:54,367|INFO   |7D6A53EA9B38|vast-csi       | >>> [DELETE] https://192.168.16.198/api/v1/folders/delete_folder/
2024-09-17 19:26:54,367|INFO   |7D6A53EA9B38|vast-csi       |     {'data': '{"path": "/export/pvc-4d9fe6b0-a16a-4587-a3c9-187bc0af2d72", '
2024-09-17 19:26:54,367|INFO   |7D6A53EA9B38|vast-csi       |              '"tenant_id": 1}',
2024-09-17 19:26:54,367|INFO   |7D6A53EA9B38|vast-csi       |      'params': None}
2024-09-17 19:26:54,385|INFO   |7D6A53EA9B38|vast-csi       | Use local mounting to delete /export/pvc-4d9fe6b0-a16a-4587-a3c9-187bc0af2d72
2024-09-17 19:26:54,386|ERROR  |7D6A53EA9B38|vast-csi       | Exception during DeleteVolume
```

**Comment by koreno** [comment]
Can you upload the full logs? This isn't making sense with the code...

**Comment by datamattsson** [comment]
[delete-log.txt](https://github.com/user-attachments/files/17034259/delete-log.txt)

The operation is being retried constantly, but this is after a fairly fresh restart of the controller pod.

**Comment by koreno** [comment]
Unforunately it seems that the log doesn't contain "DEBUG" level message, probably some misconfiguration on our end.
So we can't see the error that returns from the VMS.
Could you try manually posting the `DELETE` HTTP request (along with the data and credentials) so we can see the full error?
```
>>> [DELETE] https://192.168.16.198/api/v1/folders/delete_folder/
2024-09-17 19:50:39,256|INFO   |7BAA553F2B38|vast-csi       |     {'data': '{"path": "/export/pvc-4d9fe6b0-a16a-4587-a3c9-187bc0af2d72", '
2024-09-17 19:50:39,256|INFO   |7BAA553F2B38|vast-csi       |              '"tenant_id": 1}',
2024-09-17 19:50:39,256|INFO   |7BAA553F2B38|vast-csi       |      'params': None}
```

**Comment by datamattsson** [comment]
I'm assuming something isn't configured on the appliance?

```
> DELETE /api/v1/folders/delete_folder/ HTTP/2
> Host: 192.168.16.198
> User-Agent: curl/8.5.0
> Accept: */*
> Content-Type: application/json
> Content-Length: 89
>
< HTTP/2 400
< server: nginx
< date: Wed, 18 Sep 2024 16:49:32 GMT
< content-type: application/json
< content-length: 59
< vary: Accept, Origin, Cookie
< allow: DELETE, OPTIONS
< x-frame-options: DENY
<
* Connection #0 to host 192.168.16.198 left intact
{"detail":"Operation not permitted, trash folder disabled"}
```

**Comment by datamattsson** [comment]
I checked the Cluster -> Features ->  Trash box:

```
> DELETE /api/v1/folders/delete_folder/ HTTP/2
> Host: 192.168.16.198
> User-Agent: curl/8.5.0
> Accept: */*
> Content-Type: application/json
> Content-Length: 89
>
< HTTP/2 200
< server: nginx
< date: Wed, 18 Sep 2024 16:53:09 GMT
< content-type: application/json
< content-length: 4
< vary: Accept, Origin, Cookie
< allow: DELETE, OPTIONS
< x-frame-options: DENY
< x-content-type-options: nosniff
< strict-transport-security: max-age=31536000
< content-security-policy: default-src 'self'; font-src 'self' data:; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; object-src 'none'; frame-ancestors 'none'; upgrade-insecure-requests; block-all-mixed-content
<
* Connection #0 to host 192.168.16.198 left intact
"OK"
```

**Comment by koreno** [comment]
Did this resolve the issue then? I understand that the Trash feature was disabled on the cluster side?

**Comment by datamattsson** [comment]
Yes, this resolved the issue. Thank you!
