### ISSUE TITLE
vastcsi-2.5.0 - mount.nfs: Protocol family not supported

### ISSUE THREAD

**Issue by shaikzoheb-oi** [vast-data/vast-csi#15]
CHART: vastcsi-2.5.0

Error:

mount_options = ['nolock', 'vers=4']
    
  Warning  FailedMount  9s  kubelet  MountVolume.SetUp failed for volume "pvc" : rpc error: code = Unknown desc = [NodePublishVolume]. Mounting virtualIP:/abc/pvc failed
    detail = mount.nfs: mount(2): Protocol family not supported
             mount.nfs: Protocol family not supported

**Comment by robgirard** [comment]
Sounds like maybe your worker nodes don't have basic NFS client setup. Try installing nfs-utils on your nodes.

**Comment by shaikzoheb-oi** [comment]
@robgirard Looks like the NFS setup is not working as expected in kubernetes worker nodes. As in one of the worker node where the statefulset is running, the pvc mounting is failing and I can see below errors in that node.

1. host resolution errors
Nov 05 18:28:32 node3 rpc.gssd[4041516]: ERROR: unable to resolve x.x.x.x(virtual ip) to hostname: Name or service not known
Nov 05 18:28:32 node3 rpc.gssd[4041516]: ERROR: failed to parse nfs/clnt6dc/info
Nov 05 18:30:34 node3 rpc.gssd[4041516]: ERROR: unable to resolve x.x.x.x(virtual ip) to hostname: Name or service not known
Nov 05 18:30:34 node3 rpc.gssd[4041516]: ERROR: failed to parse nfs/clnt6dd/info

2. parsing/protocol related errors
Nov 05 18:28:32 node3 rpc.gssd[4041516]: ERROR: failed to parse nfs/clnt6dc/info
Nov 05 18:30:32 node3 kubelet[2611]:     detail = mount.nfs: mount(2): Protocol family not supported
Nov 05 18:30:32 node3 kubelet[2611]:              mount.nfs: Protocol family not supported
